CREATE DATABASE QL_VESO
GO
USE QL_VESO
GO

CREATE TABLE TYPE_LOTTERY(
	ID_TYPE			VARCHAR(10),	
	CHANNEL			NVARCHAR(200),
	PRIMARY KEY(ID_TYPE)
)
GO
CREATE TABLE AGENCY(
	ID_AGENCY	VARCHAR(10),
	NAME_AGENCY	NVARCHAR(200),
	ADDR		NVARCHAR(300),
	NUMPHONE	VARCHAR(11),
	ACTIVATE	INT
	PRIMARY KEY(ID_AGENCY)
)
GO
CREATE TABLE DEAL(
	ID_TYPE				VARCHAR(10),
	ID_AGENCY			VARCHAR(10),
	QUANTITY_RECEIVE		INT,
	QUANTITY_SELL		INT,
	DATE_RECEIVE		DATETIME,
	COMMISSION			FLOAT
	PRIMARY KEY(ID_TYPE,ID_AGENCY,DATE_RECEIVE)
)	
GO
CREATE TABLE SIGNUP_LOTTERY(
	ID_SIGN				VARCHAR(10),
	ID_AGENCY			VARCHAR(10),
	ID_TYPE				VARCHAR(10),
	DATE_SIGN			DATETIME,
	QUANTITY_SIGN		INT
	PRIMARY KEY(ID_SIGN)
)
GO
CREATE TABLE RECEIPTS(
	ID_RECEIPTS			VARCHAR(10),	
	ID_TYPE				VARCHAR(10),
	ID_AGENCY			VARCHAR(10),
	DATE_IND			DATETIME,
	DATE_RECEIPTS		DATETIME,
	PAYMENT				FLOAT,
	PRIMARY KEY(ID_RECEIPTS)
)
GO
CREATE TABLE RESULT_LOTTERY(
	ID_RESULT			VARCHAR(10),
	ID_TYPE				VARCHAR(10),
	ID_PRIZE			VARCHAR(10),	
	DATE_RESULT			DATETIME,
	NUMBER_WIN			VARCHAR(6)
	PRIMARY KEY(ID_RESULT)		
)
GO
CREATE TABLE PRIZE(
	ID_PRIZE		VARCHAR(10),
	NAME_PRIZE		NVARCHAR(200),
	REWARD			FLOAT
	PRIMARY KEY(ID_PRIZE)	
)
GO
CREATE TABLE INDEBTEDNESS(
	ID_IND			VARCHAR(10),
	ID_TYPE			VARCHAR(10),
	ID_AGENCY		VARCHAR(10),
	DATE_IND		DATETIME,
	DEBT			FLOAT
	PRIMARY KEY(ID_IND)
)
GO

ALTER TABLE DEAL
ADD CONSTRAINT FK_DEAL_TYPE_LOTTERY
FOREIGN KEY (ID_TYPE) REFERENCES TYPE_LOTTERY(ID_TYPE)
GO
ALTER TABLE DEAL
ADD CONSTRAINT FK_DEAL_AGENCY
FOREIGN KEY (ID_AGENCY) REFERENCES AGENCY(ID_AGENCY)
GO
ALTER TABLE RESULT_LOTTERY
ADD CONSTRAINT FK_RESULT_LOTTERY_TYPE_LOTTERY
FOREIGN KEY (ID_TYPE) REFERENCES TYPE_LOTTERY(ID_TYPE)
GO
ALTER TABLE RESULT_LOTTERY
ADD CONSTRAINT FK_RESULT_LOTTERY_PRIZE
FOREIGN KEY (ID_PRIZE) REFERENCES PRIZE(ID_PRIZE)
GO
ALTER TABLE RECEIPTS
ADD CONSTRAINT FK_RECEIPTS_AGENCY
FOREIGN KEY (ID_AGENCY) REFERENCES AGENCY(ID_AGENCY)
GO
ALTER TABLE SIGNUP_LOTTERY
ADD CONSTRAINT FK_SIGNUP_LOTTERY_AGENCY
FOREIGN KEY (ID_AGENCY) REFERENCES AGENCY(ID_AGENCY)
GO
ALTER TABLE INDEBTEDNESS
ADD CONSTRAINT FK_INDEBTEDNESS_AGENCY
FOREIGN KEY (ID_AGENCY) REFERENCES AGENCY(ID_AGENCY)

/******************************************STRORE PROCEDURE********************************/*
/*FUNCTION SEARCH LIST*/

CREATE PROCEDURE load_id_TYPE_LOTTERY
AS
BEGIN
	SELECT ID_TYPE, ID_TYPE+' - '+CHANNEL AS TYPE_LIST FROM TYPE_LOTTERY
END
GO

CREATE PROCEDURE load_id_PRIZE
AS
BEGIN
	SELECT ID_PRIZE, ID_PRIZE+' - '+NAME_PRIZE AS PRIZE_LIST FROM PRIZE
END
GO

CREATE PROCEDURE load_id_AGENCY
AS
BEGIN
	SELECT ID_AGENCY, ID_AGENCY+' - '+NAME_AGENCY AS AGENCY_LIST FROM AGENCY
END
GO

CREATE PROCEDURE load_id_INDEBTEDNESS
AS
BEGIN
	SELECT I.ID_IND AS ID_IND FROM INDEBTEDNESS I
	WHERE NOT EXISTS(SELECT * FROM RECEIPTS R WHERE I.ID_TYPE = R.ID_TYPE AND I.ID_AGENCY=R.ID_AGENCY AND I.DATE_IND = R.DATE_IND)
END

GO
/*FUNCTION LOADDATA*/
CREATE PROCEDURE load_TYPE_LOTTERY
AS
BEGIN
	SELECT * FROM TYPE_LOTTERY
END
GO
drop proc load_DEAL 
CREATE PROC load_DEAL
AS
BEGIN
	SELECT DEAL.ID_TYPE,DEAL.ID_AGENCY,QUANTITY_RECEIVE,QUANTITY_SELL,DATE_RECEIVE,COMMISSION,CHANNEL,NAME_AGENCY FROM DEAL JOIN TYPE_LOTTERY ON DEAL.ID_TYPE=TYPE_LOTTERY.ID_TYPE JOIN AGENCY ON DEAL.ID_AGENCY = AGENCY.ID_AGENCY ORDER BY DEAL.DATE_RECEIVE
END
GO


CREATE PROC load_SIGNUP_LOTTERY
AS
BEGIN
	SELECT * FROM SIGNUP_LOTTERY
END
GO

CREATE PROC load_PRIZE
AS
BEGIN
	SELECT * FROM PRIZE
END
GO

CREATE PROCEDURE load_AGENCY
AS
BEGIN
	SELECT * FROM AGENCY
END
GO

CREATE PROCEDURE load_RESULT_LOTTERY
AS
BEGIN
	SELECT * FROM RESULT_LOTTERY ORDER BY DATE_RESULT DESC
END
GO

CREATE PROCEDURE load_SIGN_UP_LOTTERY
AS
BEGIN
	SELECT * FROM SIGNUP_LOTTERY
END
GO

CREATE PROCEDURE load_INDEBTEDNESS
AS
BEGIN
	SELECT I.ID_IND, I.ID_TYPE,I.ID_AGENCY,I.DATE_IND,I.DEBT, A.NAME_AGENCY, T.CHANNEL FROM INDEBTEDNESS I JOIN AGENCY A ON I.ID_AGENCY = A.ID_AGENCY JOIN  TYPE_LOTTERY T ON T.ID_TYPE = I.ID_TYPE
END
GO

CREATE PROCEDURE load_RECEIPTS
AS
BEGIN
	SELECT R.ID_RECEIPTS, R.ID_TYPE,R.ID_AGENCY,R.DATE_IND, R.DATE_RECEIPTS ,R.PAYMENT, A.NAME_AGENCY, T.CHANNEL FROM RECEIPTS R JOIN AGENCY A ON R.ID_AGENCY = A.ID_AGENCY JOIN  TYPE_LOTTERY T ON T.ID_TYPE = R.ID_TYPE
END
GO


/*FUNCTION INSERT*/

CREATE PROCEDURE insert_TYPE_LOTTERY	
	@CHANNEL			NVARCHAR(200)
AS
BEGIN
	DECLARE @count INT
	DECLARE @ID_TYPE	VARCHAR(10)	
	DECLARE @NUMBER		INT
	SELECT @count = COUNT(*) FROM TYPE_LOTTERY
	IF @count = 0
		BEGIN
			SET @ID_TYPE = 'LOT001'
			INSERT INTO TYPE_LOTTERY (ID_TYPE,CHANNEL) VALUES (@ID_TYPE,@CHANNEL)
		END
	ELSE
		BEGIN
			SELECT TOP 1 @ID_TYPE = SUBSTRING(ID_TYPE, 4, LEN(ID_TYPE)-3) FROM TYPE_LOTTERY ORDER BY ID_TYPE DESC
			SET @NUMBER = CAST(@ID_TYPE AS INT)
			SET @NUMBER = @NUMBER + 1			
			IF @NUMBER < 10
				SET @ID_TYPE = 'LOT00'+ (CAST(@NUMBER AS VARCHAR))
			ELSE IF @NUMBER <100
				SET @ID_TYPE = 'LOT0'+ (CAST(@NUMBER AS VARCHAR))
			ELSE
				SET @ID_TYPE = 'LOT'+ (CAST(@NUMBER AS VARCHAR))
			INSERT INTO TYPE_LOTTERY VALUES (@ID_TYPE,@CHANNEL)
		END
END
GO

CREATE PROC insert_DEAL
	@ID_TYPE			VARCHAR(10),
	@ID_AGENCY			VARCHAR(10),
	@QUANTITY_RECEIVE	INT,
	@QUANTITY_SELL		INT,
	@DATE_RECEIVE		DATETIME,
	@COMMISSION			FLOAT

AS
BEGIN
	INSERT INTO DEAL (ID_TYPE,ID_AGENCY,QUANTITY_RECEIVE,QUANTITY_SELL,DATE_RECEIVE,COMMISSION)
	VALUES (@ID_TYPE,@ID_AGENCY,@QUANTITY_RECEIVE,@QUANTITY_SELL,@DATE_RECEIVE,@COMMISSION)
END
GO

exec insert_DEAL 'LOT005','DL002','100','0','10/17/2018','0.2'
drop PROCEDURE insert_SIGNUP_LOTTERY	
CREATE PROCEDURE insert_SIGNUP_LOTTERY	
	@ID_AGENCY			VARCHAR(10),
	@DATE_SIGN			DATETIME,
	@QUANTITY_SIGN		INT
AS
BEGIN
	DECLARE @count INT				
	DECLARE @ID_SIGN	VARCHAR(10)	
	DECLARE @NUMBER		INT
	SELECT @count = COUNT(*) FROM SIGNUP_LOTTERY
	IF @count = 0
		BEGIN
			SET @ID_SIGN = 'SUL001'
			INSERT INTO SIGNUP_LOTTERY (ID_SIGN,ID_AGENCY,DATE_SIGN,QUANTITY_SIGN) VALUES (@ID_SIGN,@ID_AGENCY,@DATE_SIGN,@QUANTITY_SIGN)
		END
	ELSE
		BEGIN
			SELECT TOP 1 @ID_SIGN = SUBSTRING(ID_SIGN, 4, LEN(ID_SIGN)-3) FROM SIGNUP_LOTTERY ORDER BY ID_SIGN DESC
			SET @NUMBER = CAST(@ID_SIGN AS INT)
			SET @NUMBER = @NUMBER + 1			
			IF @NUMBER < 10
				SET @ID_SIGN = 'SUL00'+ (CAST(@NUMBER AS VARCHAR))
			ELSE IF @NUMBER <100
				SET @ID_SIGN = 'SUL0'+ (CAST(@NUMBER AS VARCHAR))
			ELSE
				SET @ID_SIGN = 'SUL'+ (CAST(@NUMBER AS VARCHAR))
			INSERT INTO SIGNUP_LOTTERY (ID_SIGN,ID_AGENCY,DATE_SIGN,QUANTITY_SIGN) VALUES (@ID_SIGN,@ID_AGENCY,@DATE_SIGN,@QUANTITY_SIGN)
		END
END
GO

CREATE PROCEDURE insert_PRIZE		
	@NAME_PRIZE		NVARCHAR(200),
	@REWARD			FLOAT
AS
BEGIN
	DECLARE @count INT	
	DECLARE @ID_PRIZE	VARCHAR(10)	
	DECLARE @NUMBER		INT
	SELECT @count = COUNT(*) FROM PRIZE
	IF @count = 0
		BEGIN
			SET @ID_PRIZE = 'PRZ001'
			INSERT INTO PRIZE (ID_PRIZE,NAME_PRIZE,REWARD) VALUES (@ID_PRIZE,@NAME_PRIZE,@REWARD)
		END
	ELSE
		BEGIN
			SELECT TOP 1 @ID_PRIZE = SUBSTRING(ID_PRIZE, 4, LEN(ID_PRIZE)-3) FROM PRIZE ORDER BY ID_PRIZE DESC
			SET @NUMBER = CAST(@ID_PRIZE AS INT)
			SET @NUMBER = @NUMBER + 1			
			IF @NUMBER < 10
				SET @ID_PRIZE = 'PRZ00'+ (CAST(@NUMBER AS VARCHAR))
			ELSE IF @NUMBER <100
				SET @ID_PRIZE = 'PRZ0'+ (CAST(@NUMBER AS VARCHAR))
			ELSE
				SET @ID_PRIZE = 'PRZ'+ (CAST(@NUMBER AS VARCHAR))
			INSERT INTO PRIZE (ID_PRIZE,NAME_PRIZE,REWARD) VALUES (@ID_PRIZE,@NAME_PRIZE,@REWARD)
		END
END
GO

CREATE PROCEDURE insert_AGENCY	
	@NAME_AGENCY	NVARCHAR(200),
	@ADDR			NVARCHAR(300),
	@NUMPHONE		VARCHAR(11),
	@ACTIVATE		INT
AS
BEGIN
	DECLARE @count INT
	DECLARE @ID_AGENCY	VARCHAR(10)	
	DECLARE @NUMBER		INT
	SELECT @count = COUNT(*) FROM AGENCY
	IF @count = 0
		BEGIN
			SET @ID_AGENCY = 'DL001'
			INSERT INTO AGENCY (ID_AGENCY,NAME_AGENCY,ADDR,NUMPHONE,ACTIVATE) VALUES (@ID_AGENCY,@NAME_AGENCY,@ADDR,@NUMPHONE,@ACTIVATE)
		END
	ELSE
		BEGIN
			SELECT TOP 1 @ID_AGENCY = SUBSTRING(ID_AGENCY, 3, LEN(ID_AGENCY)-2) FROM AGENCY ORDER BY ID_AGENCY DESC
			SET @NUMBER = CAST(@ID_AGENCY AS INT)
			SET @NUMBER = @NUMBER + 1			
			IF @NUMBER < 10
				SET @ID_AGENCY = 'DL00'+ (CAST(@NUMBER AS VARCHAR))
			ELSE IF @NUMBER < 100
				SET @ID_AGENCY = 'DL0'+ (CAST(@NUMBER AS VARCHAR))
			ELSE
				SET @ID_AGENCY = 'DL'+ (CAST(@NUMBER AS VARCHAR))
			INSERT INTO AGENCY VALUES (@ID_AGENCY,@NAME_AGENCY,@ADDR,@NUMPHONE,@ACTIVATE)
		END
END
GO

CREATE PROCEDURE insert_RESULT_LOTTERY
	@ID_TYPE			VARCHAR(10),
	@ID_PRIZE			VARCHAR(10),	
	@DATE_RESULT		DATETIME,
	@NUMBER_WIN			VARCHAR(6)
AS
BEGIN
	DECLARE @count INT
	DECLARE @ID_RESULT	VARCHAR(10)	
	DECLARE @NUMBER		INT
	SELECT @count = COUNT(*) FROM RESULT_LOTTERY
	IF @count = 0
		BEGIN
			SET @ID_RESULT = 'RSL001'
			INSERT INTO RESULT_LOTTERY (ID_RESULT,ID_TYPE,ID_PRIZE,DATE_RESULT,NUMBER_WIN) VALUES (@ID_RESULT,@ID_TYPE,@ID_PRIZE,@DATE_RESULT,@NUMBER_WIN)
		END
	ELSE
		BEGIN
			SELECT TOP 1 @ID_RESULT = SUBSTRING(ID_RESULT, 4, LEN(ID_RESULT)-3) FROM RESULT_LOTTERY ORDER BY ID_RESULT DESC
			SET @NUMBER = CAST(@ID_RESULT AS INT)
			SET @NUMBER = @NUMBER + 1			
			IF @NUMBER < 10
				SET @ID_RESULT = 'RSL00'+ (CAST(@NUMBER AS VARCHAR))
			ELSE IF @NUMBER < 100
				SET @ID_RESULT = 'RSL0'+ (CAST(@NUMBER AS VARCHAR))
			ELSE
				SET @ID_RESULT = 'RSL'+ (CAST(@NUMBER AS VARCHAR))
			INSERT INTO RESULT_LOTTERY (ID_RESULT,ID_TYPE,ID_PRIZE,DATE_RESULT,NUMBER_WIN) VALUES (@ID_RESULT,@ID_TYPE,@ID_PRIZE,@DATE_RESULT,@NUMBER_WIN)
		END
END
GO

exec insert_RESULT_LOTTERY 'LOT001','PRZ005', '10-12-2018','28232'

CREATE PROCEDURE insert_SIGN_UP_LOTTERY	
	@ID_AGENCY			VARCHAR(10),
	@ID_TYPE			VARCHAR(10),
	@DATE_SIGN			DATETIME,
	@QUANTITY			INT
AS
BEGIN
	DECLARE @count INT
	DECLARE @ID_SIGN	VARCHAR(10)	
	DECLARE @NUMBER		INT
	SELECT @count = COUNT(*) FROM SIGNUP_LOTTERY
	IF @count = 0
		BEGIN
			SET @ID_SIGN = 'SUL001'
			INSERT INTO SIGNUP_LOTTERY (ID_SIGN,ID_AGENCY,ID_TYPE,DATE_SIGN,QUANTITY_SIGN) 
			VALUES (@ID_SIGN,@ID_AGENCY,@ID_TYPE,@DATE_SIGN,@QUANTITY)
		END
	ELSE
		BEGIN
			SELECT TOP 1 @ID_SIGN = SUBSTRING(ID_SIGN, 4, LEN(ID_SIGN)-3) 
			FROM SIGNUP_LOTTERY 
			ORDER BY ID_SIGN DESC
			SET @NUMBER = CAST(@ID_SIGN AS INT)
			SET @NUMBER = @NUMBER + 1			
			IF @NUMBER < 10
				SET @ID_SIGN = 'SUL00'+ (CAST(@NUMBER AS VARCHAR))
			ELSE IF @NUMBER <100
				SET @ID_SIGN = 'SUL0'+ (CAST(@NUMBER AS VARCHAR))
			ELSE
				SET @ID_SIGN = 'SUL'+ (CAST(@NUMBER AS VARCHAR))
			INSERT INTO SIGNUP_LOTTERY (ID_SIGN,ID_AGENCY,ID_TYPE,DATE_SIGN,QUANTITY_SIGN) 
			VALUES (@ID_SIGN,@ID_AGENCY,@ID_TYPE,@DATE_SIGN,@QUANTITY)
		END
END
GO

CREATE PROCEDURE insert_RECEIPTS	
	@ID_AGENCY			VARCHAR(10),
	@ID_TYPE			VARCHAR(10),
	@DATE_IND			DATETIME,
	@DATE_RECEIPTS		DATETIME,
	@PAYMENT			FLOAT
AS
BEGIN
	DECLARE @count INT
	DECLARE @ID_RECEIPTS	VARCHAR(10)	
	DECLARE @NUMBER		INT
	SELECT @count = COUNT(*) FROM RECEIPTS
	IF @count = 0
		BEGIN
			SET @ID_RECEIPTS = 'IDR001'
			INSERT INTO RECEIPTS(ID_RECEIPTS,ID_TYPE,ID_AGENCY,DATE_IND,DATE_RECEIPTS,PAYMENT) 
			VALUES (@ID_RECEIPTS,@ID_TYPE,@ID_AGENCY,@DATE_IND,@DATE_RECEIPTS,@PAYMENT)
		END
	ELSE
		BEGIN
			SELECT TOP 1 @ID_RECEIPTS = SUBSTRING(ID_RECEIPTS, 4, LEN(ID_RECEIPTS)-3) 
			FROM RECEIPTS 
			ORDER BY ID_RECEIPTS DESC
			SET @NUMBER = CAST(@ID_RECEIPTS AS INT)
			SET @NUMBER = @NUMBER + 1			
			IF @NUMBER < 10
				SET @ID_RECEIPTS = 'IDR00'+ (CAST(@NUMBER AS VARCHAR))
			ELSE IF @NUMBER <100
				SET @ID_RECEIPTS = 'IDR0'+ (CAST(@NUMBER AS VARCHAR))
			ELSE
				SET @ID_RECEIPTS = 'IDR'+ (CAST(@NUMBER AS VARCHAR))
			INSERT INTO RECEIPTS(ID_RECEIPTS,ID_TYPE,ID_AGENCY,DATE_IND,DATE_RECEIPTS,PAYMENT) 
			VALUES (@ID_RECEIPTS,@ID_TYPE,@ID_AGENCY,@DATE_IND,@DATE_RECEIPTS,@PAYMENT)
		END
END
GO

exec insert_RECEIPTS 'DL001','LOT002','10/18/2018','11/15/2018',540000

/*FUNCTION EDIT*/

CREATE PROCEDURE edit_TYPE_LOTTERY
	@ID_TYPE			VARCHAR(10),
	@CHANNEL			NVARCHAR(200)
AS
BEGIN
	UPDATE TYPE_LOTTERY SET CHANNEL = @CHANNEL WHERE ID_TYPE = @ID_TYPE
END
GO

CREATE PROCEDURE edit_DEAL
	@ID_TYPE			VARCHAR(10),
	@ID_AGENCY			VARCHAR(10),
	@QUANTITY_RECEIVE	INT,
	@QUANTITY_SELL		INT,
	@DATE_RECEIVE		DATETIME,
	@COMMISSION			FLOAT

AS
BEGIN
	UPDATE DEAL SET QUANTITY_RECEIVE=@QUANTITY_RECEIVE,QUANTITY_SELL=@QUANTITY_SELL,DATE_RECEIVE=@DATE_RECEIVE,COMMISSION=@COMMISSION WHERE ID_TYPE = @ID_TYPE AND ID_AGENCY=@ID_AGENCY AND DATE_RECEIVE=@DATE_RECEIVE
END
GO

CREATE PROCEDURE edit_SIGNUP_LOTTERY
	@ID_SIGN			VARCHAR(10),
	@ID_AGENCY			VARCHAR(10),
	@DATE_SIGN			DATETIME,
	@QUANTITY_SIGN		INT
AS
BEGIN
	UPDATE SIGNUP_LOTTERY SET ID_AGENCY = @ID_AGENCY, DATE_SIGN = @DATE_SIGN, QUANTITY_SIGN = @QUANTITY_SIGN WHERE ID_SIGN = @ID_SIGN
END
GO

CREATE PROCEDURE edit_PRIZE
	@ID_PRIZE		VARCHAR(10),
	@NAME_PRIZE		NVARCHAR(200),
	@REWARD			FLOAT
AS
BEGIN
	UPDATE PRIZE SET NAME_PRIZE = @NAME_PRIZE, REWARD = @REWARD WHERE ID_PRIZE = @ID_PRIZE
END
GO

CREATE PROCEDURE edit_AGENCY
	@ID_AGENCY			VARCHAR(10),
	@NAME_AGENCY		NVARCHAR(200),
	@ADDR				NVARCHAR(300),
	@NUMPHONE			VARCHAR(11),
	@ACTIVATE			INT
AS
BEGIN
	UPDATE AGENCY SET NAME_AGENCY = @NAME_AGENCY, ADDR = @ADDR, NUMPHONE = @NUMPHONE, ACTIVATE = @ACTIVATE WHERE ID_AGENCY = @ID_AGENCY
END
GO

CREATE PROCEDURE edit_Result_Lottery
	@ID_RESULT			VARCHAR(10),
	@ID_TYPE			VARCHAR(10),
	@ID_PRIZE			VARCHAR(10),	
	@DATE_RESULT		DATETIME,
	@NUMBER_WIN			VARCHAR(6)
AS
BEGIN
	UPDATE RESULT_LOTTERY SET ID_TYPE = @ID_TYPE, ID_PRIZE = @ID_PRIZE, DATE_RESULT = @DATE_RESULT, NUMBER_WIN = @NUMBER_WIN WHERE ID_RESULT = @ID_RESULT
END
GO

CREATE PROCEDURE edit_SIGN_UP_LOTTERY
	@ID_SIGN			VARCHAR(10),
	@ID_AGENCY			VARCHAR(10),
	@ID_TYPE			VARCHAR(10),
	@DATE_SIGN			DATETIME,
	@QUANTITY_SIGN		INT
AS
BEGIN
	UPDATE SIGNUP_LOTTERY 
	SET ID_AGENCY = @ID_AGENCY, DATE_SIGN = @DATE_SIGN, ID_TYPE=@ID_TYPE, QUANTITY_SIGN = @QUANTITY_SIGN 
	WHERE ID_SIGN = @ID_SIGN
END
GO


/*FUNCTION FIND*/

CREATE PROCEDURE find_TYPE_LOTTERY
	@SEARCH_BY		NVARCHAR(50),
	@VALUE			NVARCHAR(600)
AS
BEGIN
	IF @SEARCH_BY = 'ID_TYPE'
		SELECT * FROM TYPE_LOTTERY WHERE ID_TYPE LIKE '%'+@VALUE+'%'
	ELSE IF @SEARCH_BY = 'NAME_TYPE'
		SELECT * FROM TYPE_LOTTERY WHERE CHANNEL LIKE N'%'+@VALUE+'%'
END
GO

CREATE PROCEDURE find_DEAL
	@SEARCH_BY		NVARCHAR(50),
	@VALUE			NVARCHAR(600)
AS
BEGIN
	IF @SEARCH_BY = 'ID_TYPE'
		SELECT DEAL.ID_TYPE,DEAL.ID_AGENCY,QUANTITY_RECEIVE,QUANTITY_SELL,DATE_RECEIVE,COMMISSION,CHANNEL,NAME_AGENCY FROM DEAL JOIN TYPE_LOTTERY ON DEAL.ID_TYPE=TYPE_LOTTERY.ID_TYPE JOIN AGENCY ON DEAL.ID_AGENCY = AGENCY.ID_AGENCY WHERE DEAL.ID_TYPE LIKE '%'+@VALUE+'%'	
	ELSE IF @SEARCH_BY = 'ID_AGENCY'
		SELECT DEAL.ID_TYPE,DEAL.ID_AGENCY,QUANTITY_RECEIVE,QUANTITY_SELL,DATE_RECEIVE,COMMISSION,CHANNEL,NAME_AGENCY FROM DEAL JOIN TYPE_LOTTERY ON DEAL.ID_TYPE=TYPE_LOTTERY.ID_TYPE JOIN AGENCY ON DEAL.ID_AGENCY = AGENCY.ID_AGENCY WHERE DEAL.ID_AGENCY LIKE '%'+@VALUE+'%'	
END
GO

CREATE PROCEDURE find_SIGNUP_LOTTERY
	@SEARCH_BY		NVARCHAR(50),
	@VALUE			NVARCHAR(600)
AS
BEGIN
	IF @SEARCH_BY = 'ID_SIGNUP'
		SELECT * FROM SIGNUP_LOTTERY WHERE ID_SIGN = @VALUE
END
GO

CREATE PROCEDURE find_PRIZE
	@SEARCH_BY		NVARCHAR(50),
	@VALUE			NVARCHAR(600)
AS
BEGIN
	IF @SEARCH_BY = 'ID_PRIZE'
		SELECT * FROM PRIZE WHERE ID_PRIZE = @VALUE
END
GO

CREATE PROCEDURE find_AGENCY
	@SEARCH_BY		NVARCHAR(50),
	@VALUE			NVARCHAR(600)
AS
BEGIN
	IF @SEARCH_BY = 'ID_AGENCY'
		SELECT * FROM AGENCY WHERE ID_AGENCY = @VALUE
END
GO

CREATE PROCEDURE find_RESULT_LOTTERY
	@SEARCH_BY		NVARCHAR(50),
	@VALUE			NVARCHAR(600)
AS
BEGIN
	IF @SEARCH_BY = 'ID_RESULT'
		SELECT * FROM RESULT_LOTTERY WHERE ID_RESULT = @VALUE
END
GO

CREATE PROCEDURE find_INDEBTEDNESS
	@SEARCH_BY		NVARCHAR(50),
	@VALUE			NVARCHAR(600)
AS	
BEGIN
	IF @SEARCH_BY = 'ID_AGENCY'
		SELECT I.ID_IND, I.ID_TYPE,I.ID_AGENCY,I.DATE_IND,I.DEBT, A.NAME_AGENCY, T.CHANNEL FROM INDEBTEDNESS I JOIN AGENCY A ON I.ID_AGENCY = A.ID_AGENCY JOIN  TYPE_LOTTERY T ON T.ID_TYPE = I.ID_TYPE WHERE I.ID_AGENCY LIKE '%'+@VALUE+'%'	
	ELSE IF @SEARCH_BY = 'ID_TYPE'
		SELECT I.ID_IND, I.ID_TYPE,I.ID_AGENCY,I.DATE_IND,I.DEBT, A.NAME_AGENCY, T.CHANNEL FROM INDEBTEDNESS I JOIN AGENCY A ON I.ID_AGENCY = A.ID_AGENCY JOIN  TYPE_LOTTERY T ON T.ID_TYPE = I.ID_TYPE WHERE I.ID_TYPE LIKE '%'+@VALUE+'%'
	ELSE IF @SEARCH_BY = 'NAME_AGENCY'
		SELECT I.ID_IND, I.ID_TYPE,I.ID_AGENCY,I.DATE_IND,I.DEBT, A.NAME_AGENCY, T.CHANNEL FROM INDEBTEDNESS I JOIN AGENCY A ON I.ID_AGENCY = A.ID_AGENCY JOIN  TYPE_LOTTERY T ON T.ID_TYPE = I.ID_TYPE WHERE A.NAME_AGENCY LIKE '%'+@VALUE+'%'
	ELSE IF @SEARCH_BY = 'CHANNEL'
		SELECT I.ID_IND, I.ID_TYPE,I.ID_AGENCY,I.DATE_IND,I.DEBT, A.NAME_AGENCY, T.CHANNEL FROM INDEBTEDNESS I JOIN AGENCY A ON I.ID_AGENCY = A.ID_AGENCY JOIN  TYPE_LOTTERY T ON T.ID_TYPE = I.ID_TYPE WHERE T.CHANNEL LIKE '%'+@VALUE+'%'

END

GO	
CREATE PROCEDURE find_id_INDEBTEDNESS
	@VALUE		NVARCHAR(600)
AS
BEGIN
	SELECT * FROM INDEBTEDNESS WHERE ID_IND = @VALUE
END

exec find_id_INDEBTEDNESS 'IND003'


/*FUNCTION MUL ATTR FIND*/

CREATE PROCEDURE find_MUL_DEAL	
	@ID_TYPE		VARCHAR(600),
	@ID_AGENCY		VARCHAR(600),
	@DATE			DATETIME
AS
BEGIN	
		SELECT * FROM DEAL WHERE ID_TYPE = @ID_TYPE AND ID_AGENCY = @ID_AGENCY AND DATE_RECEIVE = @DATE
END
GO



/*FUNCTION DELETE*/

CREATE PROCEDURE delete_TYPE_LOTTERY
	@ID_TYPE	VARCHAR(10)
AS
BEGIN
	DELETE FROM TYPE_LOTTERY WHERE ID_TYPE=@ID_TYPE
END
GO

drop PROCEDURE delete_DEAL
CREATE PROCEDURE delete_DEAL
	@ID_TYPE			VARCHAR(10),
	@ID_AGENCY			VARCHAR(10),
	@DATE_RECEIVE		VARCHAR(10)
AS
BEGIN
	DELETE FROM DEAL WHERE ID_TYPE=@ID_TYPE AND ID_AGENCY= @ID_AGENCY AND DATE_RECEIVE = @DATE_RECEIVE
END
GO

CREATE PROCEDURE delete_SIGNUP_LOTTERY
	@ID_SIGN			VARCHAR(10)
AS
BEGIN
	DELETE FROM SIGNUP_LOTTERY WHERE ID_SIGN=@ID_SIGN
END
GO

CREATE PROCEDURE delete_PRIZE
	@ID_PRIZE			VARCHAR(10)
AS
BEGIN
	DELETE FROM PRIZE WHERE ID_PRIZE=@ID_PRIZE
END
GO

CREATE PROCEDURE delete_AGENCY
	@ID_AGENCY			VARCHAR(10)
AS
BEGIN
	DELETE FROM AGENCY WHERE ID_AGENCY=@ID_AGENCY
END
GO

exec delete_AGENCY 'DL02'

CREATE PROCEDURE delete_RESULT_LOTTERY
	@ID_RESULT			VARCHAR(10)
AS
BEGIN
	DELETE FROM RESULT_LOTTERY WHERE ID_RESULT=@ID_RESULT
END
GO

CREATE PROCEDURE delete_SIGN_UP_LOTTERY
	@ID_SIGN			VARCHAR(10)
AS
BEGIN
	DELETE FROM SIGNUP_LOTTERY WHERE ID_SIGN=@ID_SIGN
END
GO

CREATE PROCEDURE delete_RECEIPTS
	@ID_RECEIPTS			VARCHAR(10)
AS
BEGIN
	DELETE FROM RECEIPTS WHERE ID_RECEIPTS=@ID_RECEIPTS
END
GO



/*FUNCTION NGHIỆP VỤ*/
drop procedure get_QUANTITY_SIGN
/*Tinh ti le so luong nhan trong dot sau*/
CREATE PROCEDURE get_QUANTITY_SIGN
	@ID_AGENCY	VARCHAR(10),
	@ID_TYPE	VARCHAR(10)
AS
BEGIN
	DECLARE @NUM_DEAL	INT	
	DECLARE @QUANTITY	INT
	DECLARE @STATUS		INT		

	SELECT TOP(3) @NUM_DEAL = COUNT(*) FROM DEAL WHERE ID_AGENCY=@ID_AGENCY AND ID_TYPE=@ID_TYPE AND DATE_RECEIVE < GETDATE()

	IF (@NUM_DEAL = 0)
	BEGIN
		IF NOT EXISTS (SELECT QUANTITY_SIGN FROM SIGNUP_LOTTERY WHERE ID_AGENCY = @ID_AGENCY AND ID_TYPE = @ID_TYPE)
			BEGIN
				SET @STATUS = -1;
				SET @QUANTITY = '';
				SELECT @STATUS AS INSTANCE, @QUANTITY AS QUANTITY
			END
		ELSE
			BEGIN
				SET @STATUS = 0;
				SELECT TOP(1) @QUANTITY = QUANTITY_SIGN FROM SIGNUP_LOTTERY WHERE ID_AGENCY = @ID_AGENCY AND ID_TYPE = @ID_TYPE ORDER BY DATE_SIGN DESC				
				SELECT @STATUS AS INSTANCE, @QUANTITY AS QUANTITY
			END
	END
	ELSE IF(@NUM_DEAL = 1)
	BEGIN
		SET @STATUS = 1	
		SELECT TOP(1) @STATUS AS INSTANCE, * FROM DEAL WHERE ID_AGENCY=@ID_AGENCY AND ID_TYPE=@ID_TYPE ORDER BY DATE_RECEIVE DESC		
	END
	ELSE IF(@NUM_DEAL = 2)
	BEGIN
		SET @STATUS = 2
		SELECT TOP(2) @STATUS AS INSTANCE, * FROM DEAL WHERE ID_AGENCY=@ID_AGENCY AND ID_TYPE=@ID_TYPE ORDER BY DATE_RECEIVE DESC
	END
	ELSE
	BEGIN
		SET @STATUS = 3
		SELECT TOP(3) @STATUS AS INSTANCE, * FROM DEAL WHERE ID_AGENCY=@ID_AGENCY AND ID_TYPE=@ID_TYPE ORDER BY DATE_RECEIVE DESC
	END	
END
GO

/*Xu ly bang cong no khi them 1 dot moi*/

DROP TRIGGER TRG_UPDATE_deal

CREATE TRIGGER TRG_UPDATE_deal ON DEAL AFTER UPDATE AS 
BEGIN
	DECLARE @count			INT
	DECLARE @NUMBER			INT

	DECLARE @ID_IND			VARCHAR(10)
	DECLARE @ID_TYPE		VARCHAR(10)
	DECLARE @ID_AGENCY		VARCHAR(10)
	DECLARE @DATE_RECEIVE	DATETIME
	DECLARE @QUANTITY_SELL	INT	
	DECLARE	@COMMISSION		FLOAT
	DECLARE @DEBT			FLOAT

	SELECT @count = COUNT(*) FROM INDEBTEDNESS

	SELECT @ID_AGENCY = ID_AGENCY, @ID_TYPE = ID_TYPE, @QUANTITY_SELL = QUANTITY_SELL, @COMMISSION=COMMISSION, @DATE_RECEIVE =DATE_RECEIVE FROM inserted

	IF NOT EXISTS (SELECT * FROM INDEBTEDNESS WHERE ID_AGENCY=@ID_AGENCY AND ID_TYPE = @ID_TYPE AND DATE_IND = @DATE_RECEIVE)
	BEGIN		
		SET @DEBT = (@QUANTITY_SELL * 10000) - ((@QUANTITY_SELL * 10000 * @COMMISSION)/100)
		IF @count = 0
			BEGIN
				SET @DEBT = (@QUANTITY_SELL * 10000) - ((@QUANTITY_SELL * 10000 * @COMMISSION)/100)
				SET @ID_IND = 'IND001'
				INSERT INTO INDEBTEDNESS VALUES(@ID_IND,@ID_TYPE,@ID_AGENCY,@DATE_RECEIVE,@DEBT)
			END
		ELSE
			BEGIN
				SELECT TOP 1 @ID_IND = SUBSTRING(ID_IND, 4, LEN(ID_IND)-3) 
				FROM INDEBTEDNESS 
				ORDER BY ID_IND DESC
				SET @NUMBER = CAST(@ID_IND AS INT)
				SET @NUMBER = @NUMBER + 1			
				IF @NUMBER < 10
					SET @ID_IND = 'IND00'+ (CAST(@NUMBER AS VARCHAR))
				ELSE IF @NUMBER <100
					SET @ID_IND = 'IND0'+ (CAST(@NUMBER AS VARCHAR))
				ELSE
					SET @ID_IND = 'IND'+ (CAST(@NUMBER AS VARCHAR))
				INSERT INTO INDEBTEDNESS VALUES(@ID_IND,@ID_TYPE,@ID_AGENCY,@DATE_RECEIVE,@DEBT)
			END
	END
	ELSE
	BEGIN		
		SET @DEBT = (@QUANTITY_SELL * 10000) - ((@QUANTITY_SELL * 10000 * @COMMISSION)/100)			
		UPDATE INDEBTEDNESS SET DEBT = @DEBT WHERE ID_AGENCY = @ID_AGENCY AND DATE_IND = @DATE_RECEIVE AND ID_TYPE=@ID_TYPE
	END
END

EXEC insert_DEAL 'LOT002','DL001',100,0,'10/18/2018',10

/*UPDATE DEAL SET QUANTITY_SELL = 90 WHERE ID_TYPE= 'LOT001' AND ID_AGENCY = 'DL002' AND DATE_RECEIVE = '11/3/2018'*/
drop trigger TRG_DELETE_deal
CREATE TRIGGER TRG_DELETE_deal ON DEAL AFTER DELETE AS 
BEGIN
	DECLARE @ID_AGENCY		VARCHAR(10)
	DECLARE @ID_TYPE			VARCHAR(10)
	DECLARE @DATE_RECEIVE	DATETIME
	DECLARE @QUANTITY_SELL	INT	
	DECLARE	@COMMISSION		FLOAT
	DECLARE @DEBT			FLOAT	

	SELECT @ID_AGENCY = ID_AGENCY, @ID_TYPE = ID_TYPE, @QUANTITY_SELL = QUANTITY_SELL, @COMMISSION=COMMISSION, @DATE_RECEIVE =DATE_RECEIVE FROM deleted	
	SELECT TOP(1) @DEBT = DEBT FROM INDEBTEDNESS WHERE ID_AGENCY = @ID_AGENCY ORDER BY DATE_IND DESC
		
	DELETE INDEBTEDNESS WHERE ID_AGENCY = @ID_AGENCY AND DATE_IND = @DATE_RECEIVE AND @ID_TYPE = ID_TYPE
END

EXEC delete_DEAL 'LOT002','DL001','10/18/2018'

GO

/*HIỂN THỊ RA DANH SÁCH CỦA ĐẠI LÝ CHƯA TRẢ NỢ*/
CREATE PROCEDURE load_NOT_RECEIPTS
AS
BEGIN
SELECT I.ID_IND, I.ID_TYPE,I.ID_AGENCY,I.DATE_IND,I.DEBT, A.NAME_AGENCY, T.CHANNEL FROM INDEBTEDNESS I JOIN AGENCY A ON I.ID_AGENCY = A.ID_AGENCY JOIN TYPE_LOTTERY T ON T.ID_TYPE = I.ID_TYPE
WHERE NOT EXISTS(SELECT * FROM RECEIPTS R WHERE I.ID_TYPE = R.ID_TYPE AND I.ID_AGENCY=R.ID_AGENCY AND I.DATE_IND = R.DATE_IND)
END

GO

/*CHỨC NĂNG DÒ SỐ*/
CREATE PROCEDURE search_WINNER_NUMBER
	@ID_TYPE		varchar(10),
	@DATE_RESULT	datetime,
	@NUMBER_WIN		varchar(6),
	@LEN_NUMBER	int
AS
BEGIN
	IF(@LEN_NUMBER <= 5)
	BEGIN
		SELECT T.CHANNEL, R.DATE_RESULT, R.NUMBER_WIN, P.NAME_PRIZE, P.REWARD FROM RESULT_LOTTERY R JOIN PRIZE P ON R.ID_PRIZE = P.ID_PRIZE JOIN TYPE_LOTTERY T ON T.ID_TYPE = R.ID_TYPE WHERE LEN(NUMBER_WIN) = @LEN_NUMBER AND T.ID_TYPE = @ID_TYPE AND R.DATE_RESULT = @DATE_RESULT AND R.NUMBER_WIN LIKE '%'+@NUMBER_WIN
	END
	ELSE IF(@LEN_NUMBER = 6)
	BEGIN
		DECLARE @COUNT_ROW int
		SELECT @COUNT_ROW = COUNT(*) FROM RESULT_LOTTERY R JOIN PRIZE P ON R.ID_PRIZE = P.ID_PRIZE JOIN TYPE_LOTTERY T ON T.ID_TYPE = R.ID_TYPE WHERE LEN(NUMBER_WIN) = @LEN_NUMBER AND T.ID_TYPE = @ID_TYPE AND R.DATE_RESULT = @DATE_RESULT AND R.NUMBER_WIN LIKE '%'+@NUMBER_WIN
		IF(@COUNT_ROW > 0)
		BEGIN
			SELECT T.CHANNEL, R.DATE_RESULT, R.NUMBER_WIN, P.NAME_PRIZE, P.REWARD FROM RESULT_LOTTERY R JOIN PRIZE P ON R.ID_PRIZE = P.ID_PRIZE JOIN TYPE_LOTTERY T ON T.ID_TYPE = R.ID_TYPE WHERE LEN(NUMBER_WIN) = @LEN_NUMBER AND T.ID_TYPE = @ID_TYPE AND R.DATE_RESULT = @DATE_RESULT AND R.NUMBER_WIN LIKE '%'+@NUMBER_WIN
		END
		ELSE IF(@COUNT_ROW = 0)
		BEGIN
			DECLARE @NUMBER_EXTRA varchar(6)
			DECLARE @EXTRA_NAME_PRIZE nvarchar(200)
			DECLARE @EXTRA_REWARD float
			DECLARE @COUNT_ROW_EXTRA int
			SELECT @EXTRA_NAME_PRIZE = P.NAME_PRIZE, @EXTRA_REWARD = P.REWARD FROM PRIZE P WHERE P.ID_PRIZE = 'PRZ010'
			SET @NUMBER_EXTRA = RIGHT(@NUMBER_WIN,5)
			SELECT @COUNT_ROW_EXTRA = COUNT(*) FROM RESULT_LOTTERY R JOIN TYPE_LOTTERY T ON T.ID_TYPE = R.ID_TYPE WHERE LEN(NUMBER_WIN) = @LEN_NUMBER AND T.ID_TYPE = @ID_TYPE AND R.DATE_RESULT = @DATE_RESULT AND R.NUMBER_WIN LIKE '_'+@NUMBER_EXTRA
			IF(@COUNT_ROW_EXTRA > 0)
				SELECT T.CHANNEL, R.DATE_RESULT, R.NUMBER_WIN, @EXTRA_NAME_PRIZE AS NAME_PRIZE, @EXTRA_REWARD AS REWARD FROM RESULT_LOTTERY R JOIN TYPE_LOTTERY T ON T.ID_TYPE = R.ID_TYPE WHERE LEN(NUMBER_WIN) = @LEN_NUMBER AND T.ID_TYPE = @ID_TYPE AND R.DATE_RESULT = @DATE_RESULT AND R.NUMBER_WIN LIKE '_'+@NUMBER_EXTRA
			ELSE IF(@COUNT_ROW_EXTRA = 0)
			BEGIN 
				DECLARE @NUMBER_CONSOLATION_LEFT varchar(6)
				DECLARE @NUMBER_CONSOLATION_RIGHT varchar(6)
				DECLARE @CONSOLATION_NAME_PRIZE nvarchar(200)
				DECLARE @CONSOLATION_REWARD float
				DECLARE @COUNT_ROW_CONSOLATION int
				SELECT @CONSOLATION_NAME_PRIZE = P.NAME_PRIZE, @CONSOLATION_REWARD = P.REWARD FROM PRIZE P WHERE P.ID_PRIZE = 'PRZ011'
				SET @NUMBER_CONSOLATION_LEFT = LEFT(@NUMBER_WIN,5)				
				SELECT @COUNT_ROW_CONSOLATION = COUNT(*) FROM RESULT_LOTTERY R JOIN TYPE_LOTTERY T ON T.ID_TYPE = R.ID_TYPE WHERE LEN(NUMBER_WIN) = @LEN_NUMBER AND T.ID_TYPE = @ID_TYPE AND R.DATE_RESULT = @DATE_RESULT AND R.NUMBER_WIN LIKE @NUMBER_CONSOLATION_LEFT +'_'
				IF (@COUNT_ROW_CONSOLATION > 0)
					SELECT T.CHANNEL, R.DATE_RESULT, R.NUMBER_WIN, @CONSOLATION_NAME_PRIZE AS NAME_PRIZE, @CONSOLATION_REWARD AS REWARD FROM RESULT_LOTTERY R JOIN TYPE_LOTTERY T ON T.ID_TYPE = R.ID_TYPE WHERE LEN(NUMBER_WIN) = @LEN_NUMBER AND T.ID_TYPE = @ID_TYPE AND R.DATE_RESULT = @DATE_RESULT AND R.NUMBER_WIN LIKE @NUMBER_CONSOLATION_LEFT +'_'

				SET @NUMBER_CONSOLATION_LEFT = LEFT(@NUMBER_WIN,4)
				SET @NUMBER_CONSOLATION_RIGHT = RIGHT(@NUMBER_WIN,1)		
				SELECT @COUNT_ROW_CONSOLATION = COUNT(*) FROM RESULT_LOTTERY R JOIN TYPE_LOTTERY T ON T.ID_TYPE = R.ID_TYPE WHERE LEN(NUMBER_WIN) = @LEN_NUMBER AND T.ID_TYPE = @ID_TYPE AND R.DATE_RESULT = @DATE_RESULT AND R.NUMBER_WIN LIKE @NUMBER_CONSOLATION_LEFT +'_' + @NUMBER_CONSOLATION_RIGHT
				IF (@COUNT_ROW_CONSOLATION > 0)
					SELECT T.CHANNEL, R.DATE_RESULT, R.NUMBER_WIN, @CONSOLATION_NAME_PRIZE AS NAME_PRIZE, @CONSOLATION_REWARD AS REWARD FROM RESULT_LOTTERY R JOIN TYPE_LOTTERY T ON T.ID_TYPE = R.ID_TYPE WHERE LEN(NUMBER_WIN) = @LEN_NUMBER AND T.ID_TYPE = @ID_TYPE AND R.DATE_RESULT = @DATE_RESULT AND R.NUMBER_WIN LIKE @NUMBER_CONSOLATION_LEFT +'_' + @NUMBER_CONSOLATION_RIGHT
				
				SET @NUMBER_CONSOLATION_LEFT = LEFT(@NUMBER_WIN,3)
				SET @NUMBER_CONSOLATION_RIGHT = RIGHT(@NUMBER_WIN,2)		
				SELECT @COUNT_ROW_CONSOLATION = COUNT(*) FROM RESULT_LOTTERY R JOIN TYPE_LOTTERY T ON T.ID_TYPE = R.ID_TYPE WHERE LEN(NUMBER_WIN) = @LEN_NUMBER AND T.ID_TYPE = @ID_TYPE AND R.DATE_RESULT = @DATE_RESULT AND R.NUMBER_WIN LIKE @NUMBER_CONSOLATION_LEFT +'_' + @NUMBER_CONSOLATION_RIGHT
				IF (@COUNT_ROW_CONSOLATION > 0)
					SELECT T.CHANNEL, R.DATE_RESULT, R.NUMBER_WIN, @CONSOLATION_NAME_PRIZE AS NAME_PRIZE, @CONSOLATION_REWARD AS REWARD FROM RESULT_LOTTERY R JOIN TYPE_LOTTERY T ON T.ID_TYPE = R.ID_TYPE WHERE LEN(NUMBER_WIN) = @LEN_NUMBER AND T.ID_TYPE = @ID_TYPE AND R.DATE_RESULT = @DATE_RESULT AND R.NUMBER_WIN LIKE @NUMBER_CONSOLATION_LEFT +'_' + @NUMBER_CONSOLATION_RIGHT

				SET @NUMBER_CONSOLATION_LEFT = LEFT(@NUMBER_WIN,2)
				SET @NUMBER_CONSOLATION_RIGHT = RIGHT(@NUMBER_WIN,3)		
				SELECT @COUNT_ROW_CONSOLATION = COUNT(*) FROM RESULT_LOTTERY R JOIN TYPE_LOTTERY T ON T.ID_TYPE = R.ID_TYPE WHERE LEN(NUMBER_WIN) = @LEN_NUMBER AND T.ID_TYPE = @ID_TYPE AND R.DATE_RESULT = @DATE_RESULT AND R.NUMBER_WIN LIKE @NUMBER_CONSOLATION_LEFT +'_' + @NUMBER_CONSOLATION_RIGHT
				IF (@COUNT_ROW_CONSOLATION > 0)
					SELECT T.CHANNEL, R.DATE_RESULT, R.NUMBER_WIN, @CONSOLATION_NAME_PRIZE AS NAME_PRIZE, @CONSOLATION_REWARD AS REWARD FROM RESULT_LOTTERY R JOIN TYPE_LOTTERY T ON T.ID_TYPE = R.ID_TYPE WHERE LEN(NUMBER_WIN) = @LEN_NUMBER AND T.ID_TYPE = @ID_TYPE AND R.DATE_RESULT = @DATE_RESULT AND R.NUMBER_WIN LIKE @NUMBER_CONSOLATION_LEFT +'_' + @NUMBER_CONSOLATION_RIGHT
				
				SET @NUMBER_CONSOLATION_LEFT = LEFT(@NUMBER_WIN,1)
				SET @NUMBER_CONSOLATION_RIGHT = RIGHT(@NUMBER_WIN,4)		
				SELECT @COUNT_ROW_CONSOLATION = COUNT(*) FROM RESULT_LOTTERY R JOIN TYPE_LOTTERY T ON T.ID_TYPE = R.ID_TYPE WHERE LEN(NUMBER_WIN) = @LEN_NUMBER AND T.ID_TYPE = @ID_TYPE AND R.DATE_RESULT = @DATE_RESULT AND R.NUMBER_WIN LIKE @NUMBER_CONSOLATION_LEFT +'_' + @NUMBER_CONSOLATION_RIGHT
				IF (@COUNT_ROW_CONSOLATION > 0)
					SELECT T.CHANNEL, R.DATE_RESULT, R.NUMBER_WIN, @CONSOLATION_NAME_PRIZE AS NAME_PRIZE, @CONSOLATION_REWARD AS REWARD FROM RESULT_LOTTERY R JOIN TYPE_LOTTERY T ON T.ID_TYPE = R.ID_TYPE WHERE LEN(NUMBER_WIN) = @LEN_NUMBER AND T.ID_TYPE = @ID_TYPE AND R.DATE_RESULT = @DATE_RESULT AND R.NUMBER_WIN LIKE @NUMBER_CONSOLATION_LEFT +'_' + @NUMBER_CONSOLATION_RIGHT
			END
		END
	END
END

